### ISSUE TITLE
Watching a directory doesn't limit upload to the specific file changed.

### ISSUE THREAD

**Issue by jmatthewgriffis** [cullenjett/quickbase-cli#1]
When watching a directory, a change to any file will trigger upload of all files in the directory, rather than only the specific file that was changed. This wouldn't be so bad, except that if, say, you have three files in the directory and make changes to all of them, then save them all, all three files will be uploaded three times, once for each changed file, resulting in nine upload calls. And this would only get worse the more files you had. It's possible to get around this by running multiple qb sessions, each watching an individual file, but then it defeats the purpose and convenience of being able to watch a directory. Directory-watch should still be able to determine which individual files were changed and only upload those.

**Comment by cullenjett** [comment]
Hey Matt, long time no see. Happy to hear that you guys are using this tool.

You're totally right, there's no reason we should be making API calls for unchanged files -- oversight on my part. I just published v1.4.0 with that change (meaning after the initial upload, only a changed file will be sent to QuickBase instead of the entire contents of the original `qb-deploy` call), so throw a `npm i -g quickbase-cli` at your terminal and let me know if that helps.

**Comment by jmatthewgriffis** [comment]
@cullenjett Awesome! Thanks for making this change, Cullen. I tried it out and it seems to be working great. The tool is quite useful (and now even more so).

One thing, though - when I did the Terminal command, it updated past the version 1.4.0 that you mentioned to version 1.5.1, and when I do the usual deploy command on that version, it breaks with a fatal error that "URL is not a constructor" (when it tries to construct the Quick Base URL). I was able to then revert-install to version 1.4.0, and that one seems to work fine.

**Comment by cullenjett** [comment]
Assuming that what we talked about was the actual cause of your issue (the URL constructor was introduced in version 8), I made a quick change for v1.5.2 that is hopefully a little more version-friendly and works with non-bleeding edge Node users. Let me know if that's not the case and I'll dig in deeper.

**Comment by jmatthewgriffis** [comment]
Nice, man. I updated to latest (v1.5.2, as you said) and it works now. Thanks again!
